---
- hosts: staging
  become: true
  tasks:
       - name: install pip
         apt:
            name: python3-pip
            state: present
       - name: install docker-py python module
         pip3:
            name: docker-py
            state: present
       - name: deploy the container
         docker_container:
               name: node-server
               image: samba73/node-server-5000:24
               state: started
                          
