apiVersion: v1
kind: Service
metadata:
  name: node-k8s-5000
spec:
  selector:
    app: node-k8s-5000
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-k8s-5000
  labels:
    app: node-k8s-5000
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-k8s-5000
  template:
    metadata:
      labels:
        app: node-k8s-5000
    spec:
      containers:
      - name: node-server
        image: node-server-5000:24
        ports:
        - containerPort: 5000
