---
- hosts: staging
  become: true
  tasks:
       - name: install docker-py python module
         pip:
            name: docker-py
            state: present
       - name: deploy the container
         docker_container:
               name: node-server
               image: samba73/node-server-5000:24
               state: started
                          
