---
- hosts: staging
  become: true
  tasks:
       - name: deploy the container
         docker_container:
               name: node-server
               image: samba73/node-server-new:1
               state: started
                          
